[workspace]
resolver = "2"
members = [
    "crates/figurs-core",
    "crates/figurs-text",
    "crates/figurs-math",
    "crates/figurs-layout",
    "crates/figurs-render-pdf",
    "crates/figurs-render-raster",
    "crates/figurs-render-svg",
    "crates/figurs-py",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.80"

[profile.release]
lto = true
codegen-units = 1
