//! Embedded colormap data, generated by `tools/extract_colormaps.py`.
//!
//! Nothing here is built at compile time from Python/network - the `.bin` and
//! generated `_gen.rs` files are ordinary committed source. Re-run the script
//! only when the curated set of upstream colormaps changes.

pub mod categorical_gen;
pub mod registry_gen;

/// Concatenated 256x3-byte RGB tables for every [`registry_gen::CONTINUOUS`]
/// entry, indexed by `ContinuousEntry::offset`.
pub static CONTINUOUS_BLOB: &[u8] = include_bytes!("../../data/continuous.bin");
