[package]
name = "figurs-py"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "_figurs_core"
crate-type = ["cdylib"]

[dependencies]
figurs-core = { path = "../figurs-core" }
figurs-text = { path = "../figurs-text" }
figurs-math = { path = "../figurs-math" }
figurs-layout = { path = "../figurs-layout" }
figurs-render-pdf = { path = "../figurs-render-pdf" }
figurs-render-raster = { path = "../figurs-render-raster" }
figurs-render-svg = { path = "../figurs-render-svg" }
pyo3 = { version = "0.28", features = ["extension-module"] }
